### ISSUE TITLE
Resume: ERROR - NotFound

### ISSUE THREAD

**Issue by Sam-Akla** [RiadhAdrani/slick-portfolio-svelte#28]
Hey, I am getting the following error using `npm build`.  I have added the file path in `params.ts`, and it works with `npm run dev`, but `npm build` doesnt work. I do not understand why the file cannot be found eventhough its in the correct directory.

```
NotFound [Error]: Not found: /srm-akla.github.io/src/lib/md/CV_english_2024.pdf
    at resolve2 (file:///home/zippidybop/Projects/srm-akla.github.io/.svelte-kit/output/server/index.js:2896:18)
    at resolve (file:///home/zippidybop/Projects/srm-akla.github.io/.svelte-kit/output/server/index.js:2723:34)
    at #options.hooks.handle (file:///home/zippidybop/Projects/srm-akla.github.io/.svelte-kit/output/server/index.js:2962:71)
    at respond (file:///home/zippidybop/Projects/srm-akla.github.io/.svelte-kit/output/server/index.js:2721:43) {
  status: 404
}

node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /srm-akla.github.io/src/lib/md/CV_english_2024.pdf (linked from /srm-akla.github.io/resume)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///home/zippidybop/Projects/srm-akla.github.io/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
    at file:///home/zippidybop/Projects/srm-akla.github.io/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///home/zippidybop/Projects/srm-akla.github.io/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///home/zippidybop/Projects/srm-akla.github.io/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
```

Thanks!

**Comment by RiadhAdrani** [comment]
Hello,
move the file to the `static` folder and change this [`line`](https://github.com/Srm-Akla/srm-akla.github.io/blob/206a360b3855a1eaa1a218869dd0f4b70b778833/src/lib/params.ts#L86) to be `item:'CV_english_2024.pdf'`.

**Comment by Srm-Akla** [comment]
It works! Thanks!

**Comment by Sam-Akla** [comment]
It works! Thanks!
